### ISSUE TITLE
what is 'tooling'?

### ISSUE THREAD

**Issue by brujo-rojas** [dannyfritz/commit-message-emoji#10]
I'm confused as to what the Tooling commit message means.
 Thanks

**Comment by anuja-joshi** [comment]
@brujo-rojas I think, Tooling commit messages are used for commits which has added something that mechanized the process .Such as if you have configured some automated testing tools or added some auto deployment script. Basically when you have tooled(equipped) your application.

**Comment by brujo-rojas** [comment]
thanks 😄  I understand now

**Comment by dannyfritz** [comment]
Thanks for answering @anuja-joshi! 😄
