### ISSUE TITLE
Add unicode name in the table

### ISSUE THREAD

**Issue by mathieutu** [dannyfritz/commit-message-emoji#17]
It should be cool to add the real unicode name in front of emoji in the table.
Indeed, on mac we can't find the `Party popper`emoji (:tada:) with the keyword `tada`.
http://emojipedia.org/party-popper/

Thx !

**Comment by dannyfritz** [comment]
https://github.com/dannyfritz/commit-message-emoji/releases/tag/v3.0.0

**Comment by mathieutu** [comment]
Thank you !
