### ISSUE TITLE
Add improvement?

### ISSUE THREAD

**Issue by tnguyen14** [dannyfritz/commit-message-emoji#18]
Could there be one for "improvement"? It's not quite refactoring, and not quite new feature.

I don't have an emoji for it right now, and open to any suggestion.

**Comment by dannyfritz** [comment]
I'm not sure "improvement" is a good commit message. Can you give me an example of an improvement that isn't one of the emoji categories?

**Comment by mike-eason** [comment]
Improving could just be another word for **Refactoring**, which there is one for that already. :package:

**Comment by tnguyen14** [comment]
A few commits I was making was about improving the UI of the application. I suppose it could be thought of as UI refactoring. However, when thinking of refactor, I think of code refactor. Making UI changes doesn't feel like refactoring to me.

**Comment by dannyfritz** [comment]
@tnguyen14 that would fall under 💄 (cosmetic) I would think.

**Comment by tnguyen14** [comment]
Would UI behavior changes be under cosmetic as well?

**Comment by mike-eason** [comment]
It really depends on how far down the rabbit hole you want to go. UI behaviour is still UI, I'd suggest not thinking about it too much and just use 💄 (cosmetic). That being said, there's nothing stopping you from using **more than one emoji**, it might make sense to use a combination of 🔧 and 💄 .

Ultimately it's down to you to decide **what emoji fits the context**, be creative, there are [hundreds](http://www.webpagefx.com/tools/emoji-cheat-sheet/) to choose from.

**Comment by tnguyen14** [comment]
Thanks. I understand that, and am already doing something along those lines.

This issue is not a complaint in any way. It is really more just a question, to the maintainers as well as any other users of this project, if they have encountered such a need, and whether there's any suggestions for how to handle it. 

I just wanted to have a conversation, sorry if it is adding to your noise.

**Comment by dannyfritz** [comment]
I welcome these conversations, but I agree that I think it still falls under cosmetic. I have to be very careful about adding too many categories as it is already becoming very hard to remember which one to use.
