### ISSUE TITLE
No colon names referenced

### ISSUE THREAD

**Issue by acidjazz** [dannyfritz/commit-message-emoji#26]
It was frustrating having to search/remember the colon name for each of these, so I'll do a PR adding it to the table, hopefully it helps!

**Comment by acidjazz** [comment]
PR created https://github.com/dannyfritz/commit-message-emoji/pull/25

**Comment by Zhastreaus** [comment]
Long ago, the colon names lived together in harmony. 
But then everything changed when the PR #15 attacked.
Only the @dannyfritz master of all unicodes could stop them.
But when the repo need him the most, he vanished

**Comment by dannyfritz** [comment]
lol
Definitely still here. We've been conversing in #25
