### ISSUE TITLE
Accessibility icon

### ISSUE THREAD

**Issue by jlr7245** [dannyfritz/commit-message-emoji#28]
I love this idea, it's fantastic. My suggestion is to add an emoji that symbolizes accessibility fixes & so on. 

I was having a hard time coming up with an appropriate emoji, however -- feels like the wheelchair icon wouldn't really be appropriate here. Maybe 🔓 ?

**Comment by dannyfritz** [comment]
Can you explain the lock?

What about a more person focussed one like 🙌?

**Comment by joepio** [comment]
The wheelchair :wheelchair: still is [the most popular](https://www.google.nl/search?q=accessibility+icon&client=ubuntu&hs=Vso&channel=fs&dcr=0&source=lnms&tbm=isch&sa=X&ved=0ahUKEwivlvzUxp3WAhVGJ1AKHSXjA14Q_AUICigB&biw=2560&bih=1363) icon to convey accessbility. The second place goes to a person with spread arms, but I don't think there's a good emoji for that one.

**Comment by dannyfritz** [comment]
There is `hug` 🤗 and `open hands` 👐.

**Comment by Zhastreaus** [comment]
I agree more to @joepio 's ♿️ icon because of it's more familiar

**Comment by dannyfritz** [comment]
https://github.com/dannyfritz/commit-message-emoji/releases/tag/v4.1.0
