### ISSUE TITLE
Emoji for linting/indentation/code formatting

### ISSUE THREAD

**Issue by NiekPas** [dannyfritz/commit-message-emoji#34]
Title seems self-explanatory enough. It would be nice to have an emoji for indentation/whitespace/missing semicolons in JS/etc.

**Comment by NiekPas** [comment]
Maybe 🎀 ([ribbon emoji](https://emojipedia.org/ribbon/)) could be used?

**Comment by NiekPas** [comment]
I'm not sure how others are using it, but I always take 'cosmetic' to mean UI/UX/design changes.

**Comment by dannyfritz** [comment]
What OS and version are you using? Should be a font/OS thing, not a browser thing.

**Comment by NiekPas** [comment]
Right now I'm on Windows 10.

**Comment by Zhastreaus** [comment]
Aren't linting/indentation/code formatting belong to refactoring?

**Comment by Fju** [comment]
Since you can sum up those changes as cosmetic changes, I would propose the lipstick 💄 emoji.

**Comment by dannyfritz** [comment]
https://github.com/atom/atom/issues/5111

**Comment by dannyfritz** [comment]
I don't see whitespace changes requiring a separate emoji beyond refactoring. I try to keep this emoji list simple as opposed to more expansive and comprehensive.
