### ISSUE TITLE
Use unicode instead

### ISSUE THREAD

**Issue by flying-sheep** [dannyfritz/commit-message-emoji#4]
only GitHub interprets the :-codes

looks like shit everywhere else.

i never want to see `:unlock:` only `🔓`.

**Comment by dannyfritz** [comment]
I've considered this many times. It is still very hard for me to type emojis on Windows though.

I'm going to leave this open because I really want to use Unicode instead of the basecamp codes. But the basecamp codes are so much easier for me to type currently.

**Comment by flying-sheep** [comment]
well, e.g. your linked atom extension [autocomplete-emoji](https://atom.io/packages/autocomplete-emojis) already suggests unicode emoji. you just have to turn off “markdown emoji” there

**Comment by dannyfritz** [comment]
https://github.com/dannyfritz/commit-message-emoji/releases/tag/v3.0.0
