### ISSUE TITLE
Emojis are not pasteable from Github

### ISSUE THREAD

**Issue by dandv** [dannyfritz/commit-message-emoji#40]
I've just tried copy/pasting the emojis from the table, but it looks like GFM renders them with an alt text, e.g. `tada` for :tada:. Saw #4 and the README - the characters *are* Unicode, not `:basecamp:`.

**Comment by dandv** [comment]
Happy to submit a PR if adding a "Unicode" column to the table is a good idea.

🎉 Initial Commit
🔖 Version Tag
✨ New Feature 🚀
🐛 Bugfix 🕷
🔒 Security Fix
📇 Metadata
♻ Refactoring
📖 Documentation
♿ Accessibility
🏇 Performance
🎨 Cosmetic
🛠 Tooling 🔧
🔌 Integration
🚨 Tests
💩 Deprecation
🗑 Removal
🚧 Work In Progress (WIP)

**Comment by dannyfritz** [comment]
They actually already are unicode characters in the README. Unless there is a different way to escape the characters.

**Comment by dandv** [comment]
When I paste them in a text editor, I get the alt text:

![image](https://user-images.githubusercontent.com/33569/82133817-13742c00-97a5-11ea-9add-d1170420db7d.png)

**Comment by dannyfritz** [comment]
While I have confirmed the behavior you are stating, know that the characters in the README.md file are Unicode and not basecamp codes.

**Comment by xurizaemon** [comment]
@dandv couple of alternatives you can try (I also used to google this project frequently):

- I keep a "Legend" section at the top of the CHANGELOG so the meaning is documented for the project team AND emoji are readily available to copy paste.
- If you're on Linux / Gnome (think you are from the first screenshot), you can install & use the [Emoji Selector](https://github.com/dannyfritz/commit-message-emoji) Gnome extension, then use the system hotkey (SUPER+E for me) and type your commit label eg "version", "feature", "bug" as it recognises those terms.

**Comment by dannyfritz** [comment]
This is really an issue with Github. I don't think they will fix it anytime soon as they probably want to keep replacing Unicode emoji with their own for consistency and compatibility reasons.

**Comment by dannyfritz** [comment]
Looks like GitHub renders actual emoji in the README's now. Reopen if you see otherwise.
