### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by peduarte** [dannyfritz/commit-message-emoji#6]
How do you feel about introducing `refactoring` commit message emoji?

**Comment by dannyfritz** [comment]
Which one did you have in mind? Maybe one that invokes feelings of being clean.

**Comment by peduarte** [comment]
Not sure! But I was thinking of 🎨  for cleaning/tidying/refactoring code and 💄 for styling (changes that affect how it visually looks)

**Comment by dannyfritz** [comment]
I might recommend keeping refactoring under 💄

Going through emoji for construction or organization i see: 💅💪💆👷🕸🐝🏗🏭🚛🚜🎛📦🛡🔗🕉

**Comment by peduarte** [comment]
Hmm yeah that's a tricky one. Might as well keep refactoring and styling under 💄

**Comment by dannyfritz** [comment]
I've been playing around with this idea and I think I like :package: for refactoring.

**Comment by peduarte** [comment]
👍

**Comment by dannyfritz** [comment]
https://github.com/dannyfritz/commit-message-emoji/commit/f9fb01b7bd9abf75b0bda99f4a5cc71f5af90569
